"""add new column long_break_trigger_session

Revision ID: 0c22e51ea6e5
Revises: 57bce425eb8c
Create Date: 2026-08-14 12:03:26.482179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c22e51ea6e5'
down_revision: Union[str, Sequence[str], None] = '57bce425eb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('long_break_trigger_session', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'long_break_trigger_session')
    # ### end Alembic commands ###
