"""mistake in a default value

Revision ID: 830b88c9f699
Revises: fdd3b4210db9
Create Date: 2026-08-05 17:05:40.688155

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "830b88c9f699"
down_revision: Union[str, Sequence[str], None] = "fdd3b4210db9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="user_settings",
        column_name="sound_duration_secs",
        server_default=sa.text("3"),
        existing_type=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="user_settings",
        column_name="sound_duration_secs",
        server_default=None,
        existing_type=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
