"""Initial

Revision ID: b9d464d67778
Revises:
Create Date: 2026-07-26 18:07:01.938919

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9d464d67778"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("is_another_auth", sa.Boolean(), nullable=False),
        sa.CheckConstraint("email LIKE '%%@%%'", name="check_email_format"),
        sa.CheckConstraint(
            "(is_another_auth = TRUE AND hashed_password IS NULL) OR (is_another_auth = FALSE AND hashed_password IS NOT NULL)",
            name="check_password_presence_by_auth_type",
        ),
        sa.CheckConstraint("birth_date <= CURRENT_DATE", name="check_birth_date"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("IN_PROGRESS", "DONE", name="task_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("users")
    # ### end Alembic commands ###
