"""birth_date -> settings, +sound_duration_secs -> settings

Revision ID: fdd3b4210db9
Revises: 568558d01cfb
Create Date: 2026-08-03 17:18:43.538266

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdd3b4210db9"
down_revision: Union[str, Sequence[str], None] = "568558d01cfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_settings", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column(
        "user_settings", sa.Column("sound_duration_secs", sa.Integer(), nullable=True)
    )
    op.drop_column("users", "birth_date")
    op.create_check_constraint(
        constraint_name="check_birth_date",
        table_name="user_settings",
        condition="birth_date <= CURRENT_DATE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("birth_date", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.drop_column("user_settings", "sound_duration_secs")
    op.drop_column("user_settings", "birth_date")
    op.drop_constraint(
        constraint_name="check_birth_date", table_name="user_settings", type_="check"
    )
    # ### end Alembic commands ###
